mystr= "Hello this is python code "
print(mystr)
#print(mystr.capitalize())
#print(mystr.casefold())
#print("Center :",mystr.center(100))
#print("Count :",mystr.count("s"))
#print("EndWith :",mystr.endswith("e"))
#print(mystr.startswith("h"))
#print(mystr.find("this"))
#print(mystr.format(2,5))
#print(mystr.index("d"))
#print(" ".isalnum())
#print("1".isalpha())
#print("a".isdecimal())
#print("hello".isdigit())
#print("1.1".isnumeric())
#print("int".isidentifier())
#print("hello".islower())
#print("Abc".istitle())
#print("t".isupper())
#print("-".join("hello this is python code"))
#print(mystr.ljust(40,'*'))
#print(mystr.lower())
#print(mystr.upper())
#print(mystr.partition('H'))
#print(mystr.replace("H", "t"))
#print(mystr.split("o", maxsplit=2))
#print(mystr.swapcase())
print(mystr.title())